using System.Data;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using OpenBusinessPlatform.Api.Infrastructure.Persistence;
using OpenBusinessPlatform.Api.Modules.Forms;

namespace OpenBusinessPlatform.Api.Modules.Records;

public sealed class AutonumberService(OpenBusinessPlatformDbContext dbContext)
{
    public async Task ApplyAsync(Guid formId, FormSchemaDefinition schema, IDictionary<string, object?> values, CancellationToken ct)
    {
        EnsureClientValuesAbsent(schema, values);
        foreach (var field in schema.Fields.Where(field => field.Type == FormFieldTypes.Autonumber))
        {
            var config = field.Autonumber ?? new FormFieldAutonumberDefinition();
            var number = await AllocateAsync(formId, field.Id, config.StartAt, ct);
            values[field.Id] = Format(number, config);
        }
    }

    public static string Format(long number, FormFieldAutonumberDefinition config) =>
        $"{config.Prefix}{number.ToString(config.Padding > 0 ? new string('0', config.Padding) : "0", CultureInfo.InvariantCulture)}{config.Suffix}";

    public static void EnsureClientValuesAbsent(FormSchemaDefinition schema, IDictionary<string, object?> values)
    {
        var field = schema.Fields.FirstOrDefault(candidate => candidate.Type == FormFieldTypes.Autonumber && values.ContainsKey(candidate.Id));
        if (field is not null)
            throw new RecordSubmissionException(400, "Record values are invalid.", [new($"values.{field.Id}", "record.autonumber_readonly", $"'{field.Label}' is generated by the server.")]);
    }

    private async Task<long> AllocateAsync(Guid formId, string fieldId, long startAt, CancellationToken ct)
    {
        var connection = dbContext.Database.GetDbConnection();
        if (connection.State != ConnectionState.Open) await connection.OpenAsync(ct);
        await using var command = connection.CreateCommand();
        command.Transaction = dbContext.Database.CurrentTransaction?.GetDbTransaction();
        command.CommandText = """
            INSERT INTO form_autonumber_sequences (id, workspace_id, form_id, field_id, next_value, created_at, updated_at)
            VALUES (gen_random_uuid(), @workspace, @form, @field, @start + 1, NOW(), NOW())
            ON CONFLICT (workspace_id, form_id, field_id)
            DO UPDATE SET next_value = form_autonumber_sequences.next_value + 1, updated_at = NOW()
            RETURNING next_value - 1;
            """;
        Add(command, "workspace", dbContext.ActiveWorkspaceId); Add(command, "form", formId); Add(command, "field", fieldId); Add(command, "start", startAt);
        return Convert.ToInt64(await command.ExecuteScalarAsync(ct), CultureInfo.InvariantCulture);
    }

    private static void Add(System.Data.Common.DbCommand command, string name, object value) { var parameter = command.CreateParameter(); parameter.ParameterName = name; parameter.Value = value; command.Parameters.Add(parameter); }
}
