import { Download, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "../../../components/ui/Badge";
import { Button } from "../../../components/ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../../components/ui/Card";
import { Input } from "../../../components/ui/Input";
import { PageHeader } from "../../../components/ui/PageHeader";
import { useLocalization } from "../../../context/LocalizationContext";
import { exportComplianceAudit, getCompliancePosture, searchComplianceAudit, type ComplianceAuditFilters, type ComplianceAuditPage, type CompliancePosture } from "..";

const initialFilters: ComplianceAuditFilters = { page: 1, pageSize: 50 };
export function CompliancePage() {
  const { formatDateTime } = useLocalization(); const [posture, setPosture] = useState<CompliancePosture | null>(null); const [audit, setAudit] = useState<ComplianceAuditPage | null>(null); const [filters, setFilters] = useState(initialFilters); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const load = async (next = filters) => { setLoading(true); setError(""); try { const [postureResult, auditResult] = await Promise.all([getCompliancePosture(), searchComplianceAudit(next)]); setPosture(postureResult); setAudit(auditResult); } catch (value) { setError(value instanceof Error ? value.message : "Compliance data could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void load(initialFilters); }, []);
  const exportAudit = async () => { setError(""); try { const file = await exportComplianceAudit(filters); const url = URL.createObjectURL(file.blob); const link = document.createElement("a"); link.href = url; link.download = file.fileName; link.click(); URL.revokeObjectURL(url); } catch (value) { setError(value instanceof Error ? value.message : "Audit export failed."); } };
  const apply = () => { const next = { ...filters, page: 1 }; setFilters(next); void load(next); };
  const page = (number: number) => { const next = { ...filters, page: number }; setFilters(next); void load(next); };
  return <div className="grid gap-6"><PageHeader eyebrow="Enterprise" title="Compliance & audit" description="Operational posture and payload-safe workspace audit review." actions={<Button disabled={loading} onClick={() => void load()} variant="outline"><RefreshCw className="size-4" />Refresh</Button>} />
    {posture ? <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{posture.controls.map((control) => <Card key={control.key}><CardHeader><div className="flex items-start justify-between gap-3"><ShieldCheck className="size-5 text-primary" /><Badge tone={control.status === "pass" ? "success" : control.status === "warning" ? "warning" : "default"}>{control.status}</Badge></div><CardTitle>{control.title}</CardTitle><CardDescription>{control.summary}</CardDescription></CardHeader></Card>)}</div><p className="text-sm text-muted-foreground">{posture.disclaimer} Generated {formatDateTime(posture.generatedAt)}.</p></> : null}
    <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>Audit events</CardTitle><CardDescription>Before/after payloads are excluded; sensitive metadata keys are redacted.</CardDescription></div><Button onClick={() => void exportAudit()} variant="outline"><Download className="size-4" />Export CSV</Button></div></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><Input label="From" onChange={(event) => setFilters({ ...filters, from: event.target.value ? new Date(event.target.value).toISOString() : undefined })} type="datetime-local" /><Input label="To" onChange={(event) => setFilters({ ...filters, to: event.target.value ? new Date(event.target.value).toISOString() : undefined })} type="datetime-local" /><Input label="Entity type" onChange={(event) => setFilters({ ...filters, entityType: event.target.value })} value={filters.entityType ?? ""} /><Input label="Action" onChange={(event) => setFilters({ ...filters, action: event.target.value })} value={filters.action ?? ""} /></div><div className="mt-3 flex justify-end"><Button disabled={loading} onClick={apply}>Apply filters</Button></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="px-3 py-2">Time</th><th className="px-3 py-2">Action</th><th className="px-3 py-2">Entity</th><th className="px-3 py-2">Actor</th><th className="px-3 py-2">Metadata</th></tr></thead><tbody>{audit?.items.map((item) => <tr className="border-b border-border/70" key={item.id}><td className="whitespace-nowrap px-3 py-3">{formatDateTime(item.createdAt)}</td><td className="px-3 py-3 font-semibold">{item.action}</td><td className="px-3 py-3">{item.entityType}<span className="block text-xs text-muted-foreground">{item.entityId}</span></td><td className="px-3 py-3 text-xs">{item.userId ?? "system"}</td><td className="max-w-xs px-3 py-3"><code className="block truncate text-xs">{item.metadata ? JSON.stringify(item.metadata) : "—"}</code></td></tr>)}</tbody></table>{audit?.items.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No audit events match these filters.</p> : null}</div>
      {audit ? <div className="mt-4 flex items-center justify-between text-sm"><span className="text-muted-foreground">{audit.total} total event(s)</span><div className="flex gap-2"><Button disabled={audit.page <= 1 || loading} onClick={() => page(audit.page - 1)} size="sm" variant="outline">Previous</Button><Button disabled={audit.page * audit.pageSize >= audit.total || loading} onClick={() => page(audit.page + 1)} size="sm" variant="outline">Next</Button></div></div> : null}{error ? <p className="mt-4 text-sm font-semibold text-destructive">{error}</p> : null}</CardContent></Card>
  </div>;
}
